version: 2
mergeable:
  - when: issues.opened
    validate:
      - do: label
        must_exclude:
          regex: bug
    pass:
      - do: comment
        payload:
          body: >
            This is the first comment !
