version: 2
mergeable:
  - when: issues.opened
    validate:
      - do: label
        must_exclude:
          regex: bug
    pass:
      - do: comment
        payload:
          body: >
            This is the first comment !
  - when: schedule.repository
    validate:
      - do: stale
        days: 1
        type: pull_request, issues
    pass:
      - do: comment
        payload:
          body: This is old. Is it still relevant?
