version: 2
mergeable:
  - when: issues.opened
    validate:
      - do: label
        must_not_include:
          regex: bug|enhancement
    pass:
      - do: comment
        payload:
          body: >
            This is the first comment !
