version: 2
mergeable:
  - when: schedule.repository
    validate:
      - do: stale
        days: 1
        type: pull_request, issues
    pass:
      - do: comment
        payload:
          body: This is old. Is it still relevant?
  - when: issues.opened
    pass:
      - do: comment
        payload:
          body: >
            First comment for this issue
  - when: pull_request.opened
    pass:
      - do: comment
        payload:
          body: >
            First comment for this PR
